- name: Install SDKMan
  shell:
    cmd: |
      set -e
      curl -s https://get.sdkman.io | bash
    creates: ~/.sdkman/bin/sdkman-init.sh

- name: Add sdk init .zshrc
  blockinfile:
    destfile: ~/.zshrc
    insertafter: EOF
    marker: "# sdk {mark} "
    block: |
      source "$HOME/.sdkman/bin/sdkman-init.sh"

- name: Install jdk {{ jdk_version }}
  shell:
    cmd: /bin/bash -c "source ~/.sdkman/bin/sdkman-init.sh && sdk install java {{ jdk_version }}"
    creates: ~/.sdkman/candidates/java/current

- name: Install maven {{ maven_version }}
  shell:
    cmd: /bin/bash -c "source ~/.sdkman/bin/sdkman-init.sh && sdk install maven {{ maven_version }}"
    creates: ~/.sdkman/candidates/maven/current
