- name: install - create installation directory
  file:
    state: directory
    path: "{{ goroot_parent_path }}"
    mode: 0755
    owner: root
    group: root
  become: yes

- name: Download and extract golang tarball
  unarchive:
    src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    remote_src: yes
    dest: "{{ goroot_parent_path }}"
    owner: root
    group: root
    creates: "{{ goroot_parent_path }}/go/bin/go"
  become: yes

- name: Add go related environment variables to .zshrc
  blockinfile:
    destfile: ~/.zshrc
    insertafter: EOF
    marker: "# golang {mark} "
    block: |

      GO111MODULE=auto
      export GOROOT={{ goroot_parent_path }}/go
      export GOPATH=$HOME/go
      export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
