#
# some roles are commented out by default. uncomment them to install
#
- hosts: all
  roles:
    - common
    - oh-my-zsh
    - kube-tools
    # - sublime-text
    # - golang
    # - gcloud-sdk
    # - awscli-v2
    # - nvm
    # - sdkman
    # - vscode
    # - docker-ce
