#
# some roles are commented out by default. uncomment them to install
#
- hosts: all
  roles:
    - common
    - oh-my-zsh
    - kube-tools
    - minikube
    - golang
    - gcloud-sdk
    - awscli-v2
    - nvm
    - sdkman
    # - sublime-text
    # - vscode
    # - docker-ce
