- name: Install required packages
  apt:
    update_cache: yes
    pkg:
      - libasound2
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Import signing key into apt
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Add APT repository
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/vscode stable main
    filename: vscode
    state: present
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install VSCode from APT repository
  apt:
    update_cache: yes
    pkg:
      - code
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']
