- name: Download clojure installer {{ clojure_version }}
  get_url:
    url: "https://download.clojure.org/install/linux-install-{{ clojure_version }}.sh"
    dest: "~/tmp/install.sh"
    mode: 0755

- name: Run clojure installer
  shell:
    cmd: |
      set -e
      cd ~/tmp
      ./install.sh --prefix ~/.local
    creates: ~/.local/bin/clj

- name: Download Leiningen script
  get_url:
    url: "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
    dest: "~/.local/bin/lein"
    mode: 0755

- name: Run lein self-install
  shell:
    cmd: |
      set -e
      ~/.local/bin/lein self-install
    creates: ~/.lein/self-installs
