- name: ensure ~/.local/bin directory exists
  file:
    path: ~/.local/bin
    state: directory

- name: ensure ~/tmp directory exists
  file:
    path: ~/tmp
    state: directory

- name: Download kubectl binary {{ kubectl_version }}
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/{{ dpkg_arch }}/kubectl"
    dest: "{{ tools_path }}/kubectl"
    mode: 0755

- name: Download skaffold binary {{ skaffold_version }}
  get_url:
    url: "https://storage.googleapis.com/skaffold/releases/{{ skaffold_version }}/skaffold-linux-{{ dpkg_arch }}"
    dest: "{{ tools_path }}/skaffold"
    mode: 0755

- name: Download kustomize binary {{ kustomize_version }}
  unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_{{ dpkg_arch }}.tar.gz"
    remote_src: yes
    dest: ~/.local/bin
    creates: ~/.local/bin/kustomize

- name: Download k9s binary {{ k9s_version }}
  unarchive:
    src: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ ansible_architecture }}.tar.gz"
    remote_src: yes
    dest: ~/.local/bin
    creates: ~/.local/bin/k9s

- name: Download helm binary {{ helm_version }}
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-{{ dpkg_arch }}.tar.gz"
    remote_src: yes
    dest: ~/tmp
    creates: ~/tmp/inux-{{ dpkg_arch }}/helm

- name: Install helm binary
  shell:
    cmd: |
      set -e
      cp ~/tmp/linux-{{ dpkg_arch }}/helm ~/.local/bin/helm
    creates: ~/.local/bin/helm

- name: Download dapr CLI binary {{ dapr_version }}
  unarchive:
    src: "https://github.com/dapr/cli/releases/download/{{ dapr_version }}/dapr_linux_{{ dpkg_arch }}.tar.gz"
    remote_src: yes
    dest: ~/.local/bin
    creates: ~/.local/bin/dapr

- name: Download kubeval binary {{ kubeval_version }}
  unarchive:
    src: "https://github.com/instrumenta/kubeval/releases/download/{{ kubeval_version }}/kubeval-linux-{{ dpkg_arch }}.tar.gz"
    remote_src: yes
    dest: ~/.local/bin
    creates: ~/.local/bin/kubeval

- name: Download flux v2 binary {{ flux_version }}
  unarchive:
    src: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_{{ dpkg_arch }}.tar.gz"
    remote_src: yes
    dest: ~/.local/bin
    creates: ~/.local/bin/flux


- name: Download yq binary {{ yq_version }}
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_{{ dpkg_arch }}"
    dest: ~/.local/bin/yq
    mode: 0755

- name: delete useless files
  file:
    path: ~/.local/bin/{{ item }}
    state: absent
  with_items:
    - README.md
    - LICENSE