## playbook here is copied from https://github.com/veggiemonk/ansible-ohmyzsh
---
- name: Install required packages
  apt:
    update_cache: yes
    pkg:
      - git
      - peco
      - zsh
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install required packages
  yum:
    name:
      - git
      - zsh
  become: yes
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Download peco binary {{ peco_version }}
  unarchive:
    src: "https://github.com/peco/peco/releases/download/{{ peco_version }}/peco_linux_{{ dpkg_arch }}.tar.gz"
    remote_src: yes
    dest: ~/tmp
    creates: ~/tmp/peco_linux_{{ dpkg_arch }}/peco
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Install peco binary
  shell:
    cmd: |
      set -e
      cp ~/tmp/peco_linux_{{ dpkg_arch }}/peco ~/.local/bin/peco
    creates: ~/.local/bin/peco
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Clone oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: ~/.oh-my-zsh
    update: no
    depth: 1

- name: Clone oh-my-zsh custom plugins for fish shell like behavior
  git:
    repo: "{{ item.repo }}"
    dest: "~/.oh-my-zsh/custom/plugins/{{ item.dest }}"
    update: no
    depth: 1
  with_items:
    - {
        repo: "https://github.com/zsh-users/zsh-autosuggestions",
        dest: "zsh-autosuggestions",
      }
    - {
        repo: "https://github.com/jimeh/zsh-peco-history.git",
        dest: "zsh-peco-history",
      }

- name: Creating new zshrc
  template:
    src: zshrc.j2
    dest: ~/.zshrc
    mode: 0644
    force: no

- name: change user shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: yes
