- name: Import signing key into apt
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Add APT repository
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk main"
    filename: google-cloud-sdk
    state: present
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install gcloud SDK from APT repository
  apt:
    update_cache: yes
    pkg:
      - google-cloud-sdk
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']
