- name: Download Google Cloud SDK
  unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ gcloud_sdk_version }}-linux-{{ ansible_architecture }}.tar.gz
    remote_src: yes
    dest: ~/.local
    creates: ~/.local/google-cloud-sdk/bin/gcloud

- name: Add Google Cloud SDK path to .zshrc
  blockinfile:
    destfile: ~/.zshrc
    insertafter: EOF
    marker: "# gcloud-sdk {mark} "
    block: |
      export PATH=$HOME/.local/google-cloud-sdk/bin:$PATH
