- name: Download Google Cloud SDK
  unarchive:
    src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ gcloud_sdk_version }}-linux-x86_64.tar.gz
    remote_src: yes
    dest: ~/.local
    creates: ~/.local/google-cloud-sdk/bin/gcloud

- name: Add Google Cloud SDK pathto .zshrc
  blockinfile:
    destfile: ~/.zshrc
    insertafter: EOF
    marker: "# gcloud-sdk {mark} "
    block: |
      export PATH=$HOME/.local/google-cloud-sdk/bin:$PATH

- name: Install kubectl, kustomize and skaffold
  shell:
    cmd: |
      set -e
      ~/.local/google-cloud-sdk/bin/gcloud components install kubectl kustomize skaffold --quiet
    creates: ~/.local/google-cloud-sdk/bin/kustomize

