- name: Import signing key into apt
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present
  become: yes

  
- name: Add APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    filename: docker-ce
    state: present
  become: yes


- name: Install Docker CE from APT repository
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes


- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
  become: yes