- name: Import signing key into apt for Debian/Ubuntu
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Import signing key into apt for Pop!_OS
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: yes
  when: ansible_distribution in ['Pop!_OS']

  
- name: Add APT repository for Debian/Ubuntu
  apt_repository:
    repo: "deb [arch={{ dpkg_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    filename: docker-ce
    state: present
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Add APT repository for Pop!_OS
  apt_repository:
    repo: "deb [arch={{ dpkg_arch }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker-ce
    state: present
  become: yes
  when: ansible_distribution in ['Pop!_OS']


- name: Install Docker CE from APT repository
  apt:
    update_cache: yes
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']


- name: add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    append: yes
    groups: docker
  become: yes
