- name: install ASDF
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: ~/.asdf
    update: no

- name: install asdf plugin for erlang and elixir
  shell:
    cmd: |
      asdf plugin add erlang
      asdf plugin add elixir
      asdf plugin add nodejs
  ignore_errors: true

- name: Install build essentials for compiling C extensions
  apt:
    update_cache: yes
    pkg:
      - build-essential
      - libssl-dev
      - automake
      - autoconf
      - libncurses5-dev
      - libyaml-dev
      - libxslt-dev
      - libffi-dev
      - libtool
      - unixodbc-dev
      - xsltproc
      - fop
      - libwxgtk-webview3.0-gtk3-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng-dev
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']

- name: Install commonly used packages via YUM
  yum:
    name:
      - '@Development tools'
  become: yes
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']


- name: Print help
  shell:
    cmd: |
      echo asdf plugins has been installed, to install the binaries needed
      echo Create a file called .tool-versions in your project directory, e.g
      echo
      echo elixir 1.12.3-otp-24
      echo erlang 24.0.6
      echo nodejs lts-erbium
      echo
      echo then run asdf to install them
      echo   asdf install
