- name: Install nodejs package manager volta
  shell:
    cmd: |
      set -e
      curl https://get.volta.sh | bash
    creates: ~/.volta/bin/volta

- name: Add volta path to .zshrc
  blockinfile:
    destfile: ~/.zshrc
    insertafter: EOF
    marker: "# volta {mark} "
    block: |
      export PATH=$HOME/.volta/bin:$PATH