- name: Install commonly used packages via APT
  apt:
    update_cache: yes
    pkg:
      - curl
      - git
      - jq
      - peco
      - telnet
      - tmux
      - unzip
      - wget
      - zip
      - zsh
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Pop!_OS']

- name: Install commonly used packages via YUM
  yum:
    name:
      - curl
      - git
      - jq
      - rlwrap
      - telnet
      - tmux
      - unzip
      - wget
      - zip
      - zsh
  become: yes
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no
