- name: Install commonly used packages via APT
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - build-essential
      - curl
      - jq
      - git
      - python3-pip
      - telnet
      - tmux
      - unzip
      - wget
      - zip
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install commonly used packages via YUM
  yum:
    name:
      - '@Development tools'
      - curl
      - jq
      - git
      - python3-pip
      - telnet
      - tmux
      - unzip
      - wget
      - zip
  become: yes
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux']

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no

- name: check Github CLI has been installed
  shell: 
    cmd: 'which gh'
    warn: no
  register: which_gh
  ignore_errors: true

- name: Install Github CLI using deb package 
  apt:
    deb: https://github.com/cli/cli/releases/download/v{{ ghcli_version }}/gh_{{ ghcli_version }}_linux_{{ dpkg_arch }}.deb 
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu'] and which_gh.rc != 0

- name: Install Github CLI using rpm package 
  yum:
    name: https://github.com/cli/cli/releases/download/v{{ ghcli_version }}/gh_{{ ghcli_version }}_linux_{{ dpkg_arch }}.rpm 
    disable_gpg_check: yes
  become: yes
  when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux'] and which_gh.rc != 0

- name: Creates tmp directory
  file:
    path: ~/tmp
    state: directory