#
#  this box is for doing development work
#
$system_setup = <<END_OF_SETUP

yum install -y git ansible

END_OF_SETUP


$user_setup = <<END_OF_USER_SETUP

git clone https://github.com/sloppycoder/linux-dev-ansible.git

END_OF_USER_SETUP

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.box = "generic/centos8"

	config.vm.box_check_update = false

	config.vm.provider 'virtualbox' do |v|
	    v.memory = 1536
	    v.cpus = 1
	end

	config.vm.provision 'shell', inline: $system_setup
	config.vm.provision 'shell', inline: $user_setup, privileged: false

end
