- name: Install commonly used packages
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - build-essential
      - curl
      - jq
      - git
      - python3-pip
      - telnet
      - tmux
      - unzip
      - wget
      - zip
  become: yes

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no

- name: Install Github CLI using deb package 
  apt:
    deb: https://github.com/cli/cli/releases/download/v{{ ghcli_version }}/gh_{{ ghcli_version }}_linux_amd64.deb 
    state: present
  become: yes

  # TODO: add peotry to replace pipenv
  