- name: Install commonly used packages
  apt:
    update_cache: yes
    pkg:
      - curl
      - jq
      - git
      - git-gui
      - telnet
      - tmux
      - wget
  become: yes

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no
