- name: Install commonly used packages
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - build-essential
      - curl
      - jq
      - git
      - git-gui
      - python3-pip
      - telnet
      - tmux
      - unzip
      - wget
      - zip
  become: yes

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no

# pipenv not in repo for earlier version of Debian
- name: Install pipenv using apt
  apt:
    pkg:
      - pipenv
  ignore_errors: yes
  become: yes
