- name: Install commonly used packages
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - build-essential
      - curl
      - jq
      - git
      - git-gui
      - python3-pip
      - telnet
      - tmux
      - unzip
      - wget
      - zip
  become: yes

- name: Install pipenv on Debian Buster
  apt:
    pkg:
      - pipenv
  become: yes
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'

- name: Perform user install of pipenv on Ubuntu Bionic
  shell:
    cmd: python3 -m pip install --user pipenv
    creates: ~/.local/bin/pipenv
  when:
    (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'bionic') or
    (ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch')

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no

- name: Download yq binary
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64"
    dest: /usr/local/bin/yq
    owner: root
    group: root
    mode: 0755
  become: yes