- name: Install commonly used packages
  apt:
    update_cache: yes
    pkg:
      - apt-transport-https
      - build-essential
      - curl
      - jq
      - git
      - git-gui
      - python3-pip
      - telnet
      - tmux
      - unzip
      - wget
      - zip
  become: yes

- name: create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: Install pipenv using apt
  apt:
    pkg:
      - pipenv
  become: yes
  when: ansible_distribution == 'Debian' and ansible_distribution_release != 'stretch'

- name: Perform user install of pipenv
  shell:
    cmd: python3 -m pip install --user pipenv
    creates: ~/.local/bin/pipenv
  when: ansible_distribution == 'Ubuntu' or ( ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch' )

- name: Creating new .gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
    mode: 0644
    force: no

- name: Download yq binary
  get_url:
    url: "https://github.com/mikefarah/yq/releases/download/{{ yq_version }}/yq_linux_amd64"
    dest: ~/.local/bin/yq
    mode: 0755
