- name: Install required packages
  apt:
    update_cache: yes
    pkg:
      - qemu-kvm 
      - libvirt-clients 
      - libvirt-daemon-system
      - bridge-utils
      - virt-manager
  become: yes
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Download minikube binary {{ minikube_version }}
  get_url:
    url: "https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64"
    dest: "{{ tools_path }}/minikube"
    mode: 0755
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: add user to related groups
  user:
    name: "{{ ansible_user_id }}"
    groups:  
      - kvm 
      - libvirt 
      - libvirt-qemu
    append: yes
  become: yes
